networks:
  secret-store-dev:
    driver: bridge
services:
  storage-service:
    build:
      context: https://github.com/wayne3011/secret-store.git#master:source/SecretStore
      dockerfile: Dockerfile
    networks:
      - secret-store-dev
    restart: always
    ports:
      - "8080"
    depends_on:
      - pgsql-secret-storage
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./appsettings.json:/app/appsettings.json
    deploy:
      replicas: 3
  pgsql-secret-storage:
    image: postgres:latest
    container_name: pgsql-secret-storage
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: StoreSecret
    volumes:
      - secret_storage_pgdata:/var/lib/postgresql/data
    networks:
      - secret-store-dev
volumes:
  secret_storage_pgdata:
